spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro-api
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update